### PR TITLE
Update annotate.py

### PR DESCRIPTION
**Pull request by epageperron**
Adding a comment regarding automated annotations

### CODE REVIEW

**Comment by epageperron** [comment]
@larsgw ?

**Comment by larsgw** [comment]
It's very dependent on the exact header, but I guess the whole script is? Otherwise it looks fine.

**Comment by larsgw** [comment]
It won't integrate into the framework though. Since the script cannot output to stdout, I had to write a wrapper script to actually get the CoNLL. https://gitlab.com/cdli/framework/-/blob/phoenix/develop/app/tools/converter-service/src/mpat-format.py

**Comment by epageperron** [comment]
Oh I only tested outside the framework..

**Comment by epageperron** [comment]
Does it not work anymore with your wrappers? Or are you expecting this PR should remove the need of a wrapper?

**Comment by larsgw** [comment]
It will not have an affect on wrappers. You could move the changes to `__line_process` but that's not really "correct".

**Comment by larsgw** [comment]
If the change is mainly targeted at the CDLI we could also move the changes to the wrapper.

**Comment by larsgw** [comment]
I'd suggest making a function that outputs the entire output file as a string (or stream, if that's necessary for performance).

**Comment by larsgw** [comment]
Or allowing output to stdout, but that's probably more work.

**Comment by epageperron** [comment]
Can we open an issue for improvement and merge these 2 small PR now?

**Comment by larsgw** [comment]
Sure

**Pull request merged**
